services:
  - type: web
    name: stockify
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    startCommand: /bin/sh -c "php artisan migrate --force --no-interaction; php artisan db:seed --force --no-interaction; php artisan storage:link --force; php-fpm & nginx -g 'daemon off;'"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: stockify
          type: web
          property: url
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: stockify-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: stockify-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: stockify-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: stockify-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: stockify-db
          property: password

databases:
  - name: stockify-db
    plan: free
    region: singapore
